export const mdTags: Record<string, string[]> = {
  "manifesto": ["values", "ethics", "open-protocol"],
  "spec/.well-known/README.md": ["agent", "context", "example", "json", "llm", "llmfeed", "mcp", "structure"],
  "spec/CONTRIBUTING.md": ["agent", "example", "extensible", "json", "llm", "llmfeed", "mcp", "standard", "structure", "trust"],
  "spec/README.md": ["agent", "context", "example", "json", "llm", "llmfeed", "mcp", "standard", "structure", "tool", "trust", "usage"],
  "spec/docs/SUMMARY.md": ["agent", "context", "example", "json", "llm", "llmfeed", "mcp", "standard", "structure", "trust", "usage"],
  "spec/docs/badge-guidelines.md": ["agent", "implementation", "json", "llm", "llmfeed", "mcp", "structure", "trust"],
  "spec/docs/bibliography.md": ["agent", "context", "interop", "json", "llm", "llmfeed", "mcp", "metadata", "standard", "structure"],
  "spec/docs/context-versioning.md": ["agent", "context", "json", "llm", "llmfeed", "mcp", "standard"],
  "spec/docs/exec-summary-llmfeed.md": ["agent", "json", "llm", "llmfeed", "mcp", "metadata", "standard", "structure", "tool", "trust"],
  "spec/docs/foundation-wellknownMCP.md": ["agent", "context", "llm", "llmfeed", "mcp", "standard", "structure"],
  "spec/docs/how-to-publish-mcp.md": ["mcp"],
  "spec/docs/learning-path.md": ["llm", "llmfeed", "mcp"],
  "spec/docs/llm-usage-guidelines.md": ["llm", "llmfeed", "mcp", "usage"],
  "spec/docs/llmfeeds-for-llms.md": ["agent", "context", "example", "interop", "json", "llm", "llmfeed", "mcp", "metadata", "structure", "trust"],
  "spec/docs/self-descriptive-llmfeed-example.md": ["example", "llm", "llmfeed"],
  "spec/docs/signature-verification-chain.md": ["agent", "interop", "llm", "llmfeed", "mcp", "structure", "trust"],
  "spec/docs/spec-coherence.md": ["llm", "llmfeed", "mcp"],
  "spec/docs/trust-and-compliance.md": ["llm", "llmfeed", "mcp", "trust"],
  "spec/docs/ux-guidelines.md": ["agent", "context", "json", "llm", "llmfeed", "mcp", "standard", "structure", "tool", "trust"],
  "spec/docs/why-MCP.md": ["agent", "context", "json", "llm", "llmfeed", "mcp", "metadata", "structure", "trust"],
  "spec/examples/SUMMARY.md": ["agent", "context", "example", "implementation", "json", "llm", "llmfeed", "mcp", "metadata", "trust", "usage"],
  "spec/examples/badges/index.md": ["agent", "context", "llm", "llmfeed", "mcp", "standard", "tool", "trust"],
  "spec/examples/notes/Note for GitHub Admins – LLM-Compatible Feed Export.md": ["agent", "example", "extensible", "json", "llm", "llmfeed", "mcp", "metadata", "standard", "structure", "tool", "trust"],
  "spec/export-kit/Export Kit – LLMFeed Implementation Bundle.md": ["implementation", "json", "llm", "llmfeed", "mcp", "standard", "structure", "tool", "trust"],
  "spec/note/Note-for-GitHub-Admins.md": ["agent", "json", "llm", "llmfeed", "mcp", "metadata", "standard", "structure", "trust"],
  "spec/spec/agent-behaviour.md": ["agent", "context", "json", "llm", "llmfeed", "mcp", "metadata", "standard", "structure", "trust"],
  "spec/spec/llmfeed-block-reference.md": ["agent", "context", "implementation", "json", "llm", "llmfeed", "mcp", "metadata", "structure", "trust"],
  "spec/spec/llmfeed.md": ["agent", "context", "example", "implementation", "json", "llm", "llmfeed", "mcp", "metadata", "structure", "trust", "usage"],
  "spec/spec/llmfeed_enriched.md": ["agent", "context", "extensible", "implementation", "llm", "llmfeed", "mcp", "standard", "structure", "tool", "trust"],
  "spec/spec/llmfeed_extensions.md": ["agent", "context", "example", "extensible", "interop", "json", "llm", "llmfeed", "mcp", "metadata", "standard", "structure", "tool", "trust", "usage"],
  "spec/spec/mime/llmfeed-mime.md": ["agent", "context", "example", "extensible", "json", "llm", "llmfeed", "mcp", "standard", "structure", "tool", "usage"],
  "vision": ["philosophy", "interoperability", "llm"],
};
